"""empty message

Revision ID: 942e15af0ee4
Revises: 
Create Date: 2019-11-29 17:20:25.677927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942e15af0ee4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('another_column', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('student_courses', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_another_column'), 'user', ['another_column'], unique=False)
    op.create_index(op.f('ix_user_student_courses'), 'user', ['student_courses'], unique=False)
    op.drop_column('user', 'course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('course', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_user_student_courses'), table_name='user')
    op.drop_index(op.f('ix_user_another_column'), table_name='user')
    op.drop_column('user', 'student_courses')
    op.drop_column('user', 'another_column')
    # ### end Alembic commands ###
